spring:
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:/C/practice/MyTicket/ticketing-system/src/main/resources/data;AUTO_SERVER=true
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/MyTicket
#    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088
